#!/usr/bin/env python
import os
import json
import subprocess

with open("config.json") as conf:
    config = json.load(conf)

snake_out = os.path.join(config['log'], "snake.out")
snake_err = os.path.join(config['log'], "snake.err")

with open(snake_out, 'w') as out, open(snake_err, 'w') as err:
    snake = subprocess.check_call(
        [
            "snakemake",
            "--snakefile", os.path.join(config['src'], 'Snakefile'),
            "--directory", config['work_dir'],
            "-j", "10",
        ],
        stdout=out, stderr=err
    )
