#!/bin/bash

if [ ! $# -eq 1 ] ; then
	echo "Usage: qcprot <workdir>" 1>&2
	exit 1
fi

if [ $1 = "-h" ] || [ $1 = "--help" ] ; then
	echo "Usage: qcprot <workdir>"
	exit 0
fi

if [ ! -d $1 ] ; then
	echo "Invalid workdir: $1" 1>&2
	exit 1
fi

# fail if any command exits with nonzero
set -e

WORKDIR=$(readlink -f $1)
# Directory where the script is stored.
# See https://stackoverflow.com/questions/59895/
SCRIPTDIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [ ! -f ${SCRIPTDIR}/Snakefile ] ; then
	echo "Could not find snakefile in ${SCRIPTDIR}" 1>&2
	exit 1
fi

echo "loading module files..."

module load lib/openms/1.11
module load bio/xtandem
module load bio/myrimatch
module load math/R

echo "module files loaded."

# Anaconda is a python distribution (http://continuum.io/)
# Snakemake must be installed.
export PATH=/lustre_cfc/software/qbic/anaconda3/bin:$PATH

export R_HOME=${SCRIPTDIR}/r_scripts

#snakemake -T --snakefile ${SCRIPTDIR}/Snakefile --config R_home=${WORKDIR}/r_scripts
snakemake -T --snakefile ${SCRIPTDIR}/Snakefile --cluster "ssh u-003-scfe03 'qsub -l nodes=1:ppn=1:cfc -w ${WORKDIR}' " --jobscript ${SCRIPTDIR}/jobscript.sh --config R_home=${WORKDIR}/r_scripts -j 4
